# Generated by Django 4.2.7 on 2023-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=200)),
                ('fecha', models.DateField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
    ]
