# Generated by Django 4.2.7 on 2023-12-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('idAu', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nomAu', models.CharField(max_length=200)),
                ('apellAu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Editoriales',
            fields=[
                ('idEdi', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nomEdi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=200)),
                ('fecha', models.DateField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUs', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nomUsu', models.CharField(max_length=200)),
                ('apellUsu', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
            ],
        ),
    ]
