# Generated by Django 4.2.7 on 2023-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('idAu', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nomAu', models.CharField(max_length=200)),
                ('apellAu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUs', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nomUsu', models.CharField(max_length=200)),
                ('apellUsu', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
            ],
        ),
    ]
